# Generated by Django 5.1.1 on 2024-09-28 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_job_post_cluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee_Cluster",
            fields=[
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="mainapp.employee",
                    ),
                ),
                (
                    "cluster",
                    models.IntegerField(blank=True, null=True, verbose_name="Cluster"),
                ),
                (
                    "clusterable_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Clusterable Text"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobPost_Cluster",
            fields=[
                (
                    "jobpost",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="mainapp.job_post",
                    ),
                ),
                (
                    "cluster",
                    models.IntegerField(blank=True, null=True, verbose_name="Cluster"),
                ),
                (
                    "clusterable_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Clusterable Text"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="employee",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="clusterable_text",
        ),
        migrations.RemoveField(
            model_name="job_post",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="job_post",
            name="clusterable_text",
        ),
    ]
