# Generated by Django 5.1.1 on 2024-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_cluster_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster_records",
            name="added_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
