# Generated by Django 5.1.1 on 2024-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_cluster_records_test_id_cluster_records_timestamp"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cluster_records",
        ),
    ]
